# Methods in Numpy

In [1]:
import numpy as np

In [2]:
x = np.random.randint(1,50,24)

In [6]:
x

array([18,  6, 23,  9, 24, 32, 38,  6, 38, 39, 43, 11,  3, 30, 38, 46,  1,
       10,  5, 18,  1, 18, 23, 40])

In [3]:
np.shape(x)

(24,)

In [4]:
x.shape

(24,)

In [5]:
np.min(x)

1

In [7]:
np.max(x)

46

In [8]:
np.sum(x)

520

In [9]:
np.mean(x)

21.666666666666668

In [10]:
np.median(x)

20.5

In [11]:
np.std(x)

14.564988461680597

In [12]:
np.var(x)

212.1388888888889

In [13]:
np.sort(x)

array([ 1,  1,  3,  5,  6,  6,  9, 10, 11, 18, 18, 18, 23, 23, 24, 30, 32,
       38, 38, 38, 39, 40, 43, 46])

In [14]:
x

array([18,  6, 23,  9, 24, 32, 38,  6, 38, 39, 43, 11,  3, 30, 38, 46,  1,
       10,  5, 18,  1, 18, 23, 40])

In [15]:
np.max(x)

46

In [16]:
# index of max element
np.argmax(x)

15

In [17]:
np.min(x)

1

In [18]:
# index of min element
np.argmin(x)

16

In [19]:
np.argsort(x)

array([20, 16, 12, 18,  1,  7,  3, 17, 11, 21, 19,  0,  2, 22,  4, 13,  5,
       14,  8,  6,  9, 23, 10, 15], dtype=int64)

In [20]:
np.reshape(x, (4,6))

array([[18,  6, 23,  9, 24, 32],
       [38,  6, 38, 39, 43, 11],
       [ 3, 30, 38, 46,  1, 10],
       [ 5, 18,  1, 18, 23, 40]])

In [22]:
np.reshape(x, (6,4))

array([[18,  6, 23,  9],
       [24, 32, 38,  6],
       [38, 39, 43, 11],
       [ 3, 30, 38, 46],
       [ 1, 10,  5, 18],
       [ 1, 18, 23, 40]])

In [23]:
np.reshape(x, (3,8))

array([[18,  6, 23,  9, 24, 32, 38,  6],
       [38, 39, 43, 11,  3, 30, 38, 46],
       [ 1, 10,  5, 18,  1, 18, 23, 40]])

In [24]:
x.reshape((-1, 6))

array([[18,  6, 23,  9, 24, 32],
       [38,  6, 38, 39, 43, 11],
       [ 3, 30, 38, 46,  1, 10],
       [ 5, 18,  1, 18, 23, 40]])

In [25]:
x.reshape((3,-1))

array([[18,  6, 23,  9, 24, 32, 38,  6],
       [38, 39, 43, 11,  3, 30, 38, 46],
       [ 1, 10,  5, 18,  1, 18, 23, 40]])

In [26]:
y = x.reshape((4, -1))

In [27]:
y

array([[18,  6, 23,  9, 24, 32],
       [38,  6, 38, 39, 43, 11],
       [ 3, 30, 38, 46,  1, 10],
       [ 5, 18,  1, 18, 23, 40]])

In [28]:
y.min()

1

In [29]:
y.sum()

520

In [30]:
# minimum in each column
y.min(axis=0)

array([ 3,  6,  1,  9,  1, 10])

In [31]:
y.max(axis=0)

array([38, 30, 38, 46, 43, 40])

In [32]:
# sum of each row
y.sum(axis=1)

array([112, 175, 128, 105])

In [33]:
y.mean(axis=1)

array([18.66666667, 29.16666667, 21.33333333, 17.5       ])

In [34]:
y.mean(axis=0)

array([16.  , 15.  , 25.  , 28.  , 22.75, 23.25])

In [35]:
# converts data into 1D
y.flatten()

array([18,  6, 23,  9, 24, 32, 38,  6, 38, 39, 43, 11,  3, 30, 38, 46,  1,
       10,  5, 18,  1, 18, 23, 40])

In [37]:
y.shape

(4, 6)

In [40]:
x

array([18,  6, 23,  9, 24, 32, 38,  6, 38, 39, 43, 11,  3, 30, 38, 46,  1,
       10,  5, 18,  1, 18, 23, 40])

In [43]:
# returns index where x > 30
np.where(x > 30)

(array([ 5,  6,  8,  9, 10, 14, 15, 23], dtype=int64),)

In [44]:
np.where(y > 30)

(array([0, 1, 1, 1, 1, 2, 2, 3], dtype=int64),
 array([5, 0, 2, 3, 4, 2, 3, 5], dtype=int64))

In [45]:
y

array([[18,  6, 23,  9, 24, 32],
       [38,  6, 38, 39, 43, 11],
       [ 3, 30, 38, 46,  1, 10],
       [ 5, 18,  1, 18, 23, 40]])

In [46]:
np.where(y > 30, y + 10, y)

array([[18,  6, 23,  9, 24, 42],
       [48,  6, 48, 49, 53, 11],
       [ 3, 30, 48, 56,  1, 10],
       [ 5, 18,  1, 18, 23, 50]])

In [47]:
y

array([[18,  6, 23,  9, 24, 32],
       [38,  6, 38, 39, 43, 11],
       [ 3, 30, 38, 46,  1, 10],
       [ 5, 18,  1, 18, 23, 40]])

In [55]:
row = np.array([[101,102,103,104,105,106]])
col = np.array([[99],[98],[97],[96]])

In [56]:
np.vstack((y, row))

array([[ 18,   6,  23,   9,  24,  32],
       [ 38,   6,  38,  39,  43,  11],
       [  3,  30,  38,  46,   1,  10],
       [  5,  18,   1,  18,  23,  40],
       [101, 102, 103, 104, 105, 106]])

In [57]:
np.hstack((y, col))

array([[18,  6, 23,  9, 24, 32, 99],
       [38,  6, 38, 39, 43, 11, 98],
       [ 3, 30, 38, 46,  1, 10, 97],
       [ 5, 18,  1, 18, 23, 40, 96]])

In [58]:
np.r_[y, row]

array([[ 18,   6,  23,   9,  24,  32],
       [ 38,   6,  38,  39,  43,  11],
       [  3,  30,  38,  46,   1,  10],
       [  5,  18,   1,  18,  23,  40],
       [101, 102, 103, 104, 105, 106]])

In [59]:
np.c_[y, col]

array([[18,  6, 23,  9, 24, 32, 99],
       [38,  6, 38, 39, 43, 11, 98],
       [ 3, 30, 38, 46,  1, 10, 97],
       [ 5, 18,  1, 18, 23, 40, 96]])