In [1]:
import numpy as np

# Ways to create array

In [2]:
np.array([3,5,1,6,8,12,])

array([ 3,  5,  1,  6,  8, 12])

In [3]:
x = np.array([[3,2,4,6],[1,2,4,5],[2,2,7,12]])

In [4]:
x

array([[ 3,  2,  4,  6],
       [ 1,  2,  4,  5],
       [ 2,  2,  7, 12]])

In [5]:
x + 5

array([[ 8,  7,  9, 11],
       [ 6,  7,  9, 10],
       [ 7,  7, 12, 17]])

In [6]:
x - 1

array([[ 2,  1,  3,  5],
       [ 0,  1,  3,  4],
       [ 1,  1,  6, 11]])

In [7]:
np.arange(1,11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [8]:
np.arange(2,21,2)

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [14]:
np.arange(2, 21, 2, dtype='float32')

array([ 2.,  4.,  6.,  8., 10., 12., 14., 16., 18., 20.], dtype=float32)

In [17]:
# linspace = linear space
np.linspace(2, 20, num=25, retstep=True)

(array([ 2.  ,  2.75,  3.5 ,  4.25,  5.  ,  5.75,  6.5 ,  7.25,  8.  ,
         8.75,  9.5 , 10.25, 11.  , 11.75, 12.5 , 13.25, 14.  , 14.75,
        15.5 , 16.25, 17.  , 17.75, 18.5 , 19.25, 20.  ]),
 0.75)

In [18]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [19]:
np.zeros([4,4])

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [20]:
np.ones(4)

array([1., 1., 1., 1.])

In [22]:
np.ones([4,6])

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [23]:
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [24]:
x

array([[ 3,  2,  4,  6],
       [ 1,  2,  4,  5],
       [ 2,  2,  7, 12]])

In [25]:
# will generate array of zeros of x dimension
np.zeros_like(x)

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [27]:
# will return a random number b/w 0 to 1
np.random.random()

0.5655627741465267

In [28]:
# will return array with 5 random numbers
np.random.random(5)

array([0.59341465, 0.54055714, 0.83038054, 0.03136836, 0.1934179 ])

In [29]:
# will return array of 4,4 dimension of random numbers
np.random.random([4,4])

array([[0.93321435, 0.01337999, 0.3002849 , 0.35239903],
       [0.35043681, 0.75785264, 0.25034823, 0.18885937],
       [0.40066761, 0.34065061, 0.12176093, 0.27235662],
       [0.07967693, 0.5954216 , 0.36201278, 0.48618266]])

In [31]:
np.random.randn()

-1.0571819469167554

In [32]:
np.random.randn(4)

array([-0.81265914,  1.37538912,  0.5763486 ,  0.13858927])

In [34]:
np.random.randn(4,4)

array([[ 0.12178898,  0.58290963,  0.60335466,  0.01699502],
       [ 0.22150913,  0.43352201,  0.73878678,  0.02403251],
       [ 1.05595667,  1.8705838 , -1.32758497,  0.42470974],
       [ 0.29935178, -0.1424875 , -0.20689985,  0.2460898 ]])

In [35]:
np.random.randint(1,100)

38

In [36]:
np.random.randint(1,100,10)

array([42, 96, 32,  5, 10, 97, 53, 31, 27, 68])

In [37]:
np.random.randint(1,100,[4,6])

array([[30, 17,  3, 98, 64, 56],
       [33, 79, 63, 81, 68, 40],
       [21,  3, 58, 54, 51, 14],
       [96,  9, 55, 45, 45,  1]])

# Indexing and slicing

In [38]:
x = np.random.randint(1,100,20)

In [39]:
x

array([66, 79, 31, 85, 60, 53, 64, 58, 91, 63, 81, 27, 87, 43, 47, 95, 73,
       77, 22, 50])

In [40]:
x[0]

66

In [41]:
x[-1]

50

In [42]:
x[0:5]

array([66, 79, 31, 85, 60])

In [43]:
x[0:10:2]

array([66, 31, 60, 64, 91])

In [44]:
x = np.random.randint(1,100,[4,6])

In [45]:
x

array([[35,  9, 53, 35, 23, 10],
       [53, 45, 83, 51, 66, 86],
       [87, 99, 29, 64, 73, 17],
       [99, 42, 13, 43, 51, 42]])

In [46]:
# return 0th row
x[0]

array([35,  9, 53, 35, 23, 10])

In [47]:
x[0][0]

35

In [49]:
x[3][2]

13

In [50]:
x[2]

array([87, 99, 29, 64, 73, 17])

In [51]:
x[0:2]

array([[35,  9, 53, 35, 23, 10],
       [53, 45, 83, 51, 66, 86]])

In [52]:
x[:, 0]

array([35, 53, 87, 99])

In [53]:
x[:, 0:2]

array([[35,  9],
       [53, 45],
       [87, 99],
       [99, 42]])

In [54]:
x[1:3, 2:4]

array([[83, 51],
       [29, 64]])

In [55]:
x = np.random.randint(1,100,[3,6,4])

In [56]:
x

array([[[84,  3, 54, 77],
        [58, 32, 72,  5],
        [85, 15, 38, 66],
        [92, 77, 61, 82],
        [59, 18, 18, 61],
        [ 2, 73, 24, 59]],

       [[34, 59, 49, 90],
        [12,  5, 92, 19],
        [69, 74, 20, 94],
        [48, 83, 71, 79],
        [34, 92, 81, 85],
        [ 3, 61, 87, 68]],

       [[80,  4, 69, 31],
        [99, 43, 54,  3],
        [11, 37, 29, 14],
        [79, 65, 37, 45],
        [97, 37, 84, 13],
        [71, 71, 97, 61]]])

In [57]:
x[0]

array([[84,  3, 54, 77],
       [58, 32, 72,  5],
       [85, 15, 38, 66],
       [92, 77, 61, 82],
       [59, 18, 18, 61],
       [ 2, 73, 24, 59]])

In [58]:
x[:,:,-1]

array([[77,  5, 66, 82, 61, 59],
       [90, 19, 94, 79, 85, 68],
       [31,  3, 14, 45, 13, 61]])

In [59]:
x[0,:,-1]

array([77,  5, 66, 82, 61, 59])

In [61]:
x[:,:,3:4]

array([[[77],
        [ 5],
        [66],
        [82],
        [61],
        [59]],

       [[90],
        [19],
        [94],
        [79],
        [85],
        [68]],

       [[31],
        [ 3],
        [14],
        [45],
        [13],
        [61]]])

In [62]:
x[0,:,3:4]

array([[77],
       [ 5],
       [66],
       [82],
       [61],
       [59]])